apiVersion: v1
kind: ConfigMap
metadata:
  name: progresoacademico-config
  namespace: dev-progreso-namespace
data:
  bd.host: "192.168.201.49"
  bd.port: "1522"
  bd.servicename: "g4ac121ae9018be_adbdev_tp.adb.oraclecloud.com"
  standard.datasource.url:  "jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=${bd.port})(host=${bd.host}))(connect_data=(service_name=${bd.servicename}))(security=(ssl_server_dn_match=no)))"
  standard.datasource.hikari.minimum-idle: "10"
  standard.datasource.hikari.maximum-pool-size: "50"
  standard.datasource.hikari.connectionTimeout: "10000"
  standard.datasource.hikari.idle-timeout: "120000"
  standard.datasource.hikari.max-lifetime: "300000"
  standard.datasource.hikari.validation-timeout: "10000"
  standard.datasource.hikari.connection-test-query: "SELECT 1"
  standard.datasource.hikari.initialization-fail-timeout: "1"
  standard.datasource.hikari.keep-alive-time: "120000"
  cache.duracionMinima: "1"
  cache.duracionMedia: "2"
  cache.duracionMaxima: "3"
  cache.duracion.login: "30"
  certificado_listado_api_url: "http://10.255.246.101/certificado-listado-service"
  certificado_genera_api_url: "http://10.255.246.101/certificado-genera-service"
  management.endpoint.health.show-details: "always"
  management.endpoints.web.exposure.include: "*"
  management.endpoints.web.exposure.exclude: "conditions,shutdown"