apiVersion: apps/v1
kind: Deployment
metadata:
  name: progresoacademico-app-deployment
  namespace: dev-progreso-namespace
  labels:
    app: progresoacademico-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: progresoacademico-app
  template:
    metadata:
      labels:
        app: progresoacademico-app
    spec:
      containers:
      - name: progresoacademico-app
        image: scl.ocir.io/axtkyrdgjlws/desarrollo/progresoacademico/pa-backend:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "250m"
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: progresoacademico-config
        - secretRef:
            name: progresoacademico-secret
