apiVersion: v1
kind: Service
metadata:
  name: progresoacademico-lb-service
  namespace: qa-progresoacademico
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-enable-http2: "true"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-ssl-protocols: "TLSv1.2,TLSv1.3"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: "backend-tls"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.sa-santiago-1.aaaaaaaaccikvwaayqdghlmljscxczupri4qrcpalpgmthfhr7efjlyvwdna"
spec:
  type: LoadBalancer
  selector:
    app: progresoacademico
  ports:
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Cluster