apiVersion: v1
kind: ConfigMap
metadata:
  name: progresoacademico-config
  namespace: prd-progreso-namespace
data:
  bd.host: "192.168.201.26"
  bd.port: "1522"
  bd.servicename: "g4ac121ae9018be_adbprd_tp.adb.oraclecloud.com"
  standard.datasource.url:  "jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=${bd.port})(host=${bd.host}))(connect_data=(service_name=${bd.servicename}))(security=(ssl_server_dn_match=no)))"
  standard.datasource.hikari.minimum-idle: "10"
  standard.datasource.hikari.maximum-pool-size: "400"
  standard.datasource.hikari.connectionTimeout: "60000"
  standard.datasource.hikari.idle-timeout: "300000"
  standard.datasource.hikari.max-lifetime: "120000"
  standard.datasource.hikari.validation-timeout: "300000"
  
  cache.duracionMinima: "1"
  cache.duracionMedia: "2"
  cache.duracionMaxima: "30"
  cache.duracion.login: "30"
  certificado_listado_api_url: "http://api-prd.duoc.cl/certificado-listado-service/v1"
  certificado_genera_api_url: "http://api-prd.duoc.cl/certificado-genera-service/v1"
  management.endpoint.health.show-details: "always"
  management.endpoints.web.exposure.include: "*"
  management.endpoints.web.exposure.exclude: "conditions,shutdown"