apiVersion: v1
kind: Service
metadata:
  name: prd-progresoacademico-svc
  namespace: prd-progreso-namespace
spec:
  selector:
    app: progresoacademico-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP