apiVersion: v1
kind: Service
metadata:
  name: qa-progresoacademico-svc
  namespace: qa-progreso-namespace
spec:
  selector:
    app: progresoacademico-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
