apiVersion: v1
kind: Service
metadata:
    name: qa-progresoacademico-svc
    namespace: qa-progreso-namespace
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    type: ClusterIP
    selector:
        app: progresoacademico-app


