apiVersion: apps/v1
kind: Deployment
metadata:
  name: progresoacademico-deployment
  labels:
    app: progresoacademico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progresoacademico
  template:
    metadata:
      labels:
        app: progresoacademico
    spec:
      containers:
      - name: progresoacademico
        image: scl.ocir.io/axtkyrdgjlws/qa/progresoacademico/pa-backend:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "250m"
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        env:
        - name: bd.host
          value: "192.168.201.80"
        - name: bd.port
          value: "1522"
        - name: bd.servicename
          value: "g4ac121ae9018be_adbqas_tp.adb.oraclecloud.com"
        - name: bd.usuario
          value: "BDT_PROGRESO_ACADEMICO"
        - name: bd.password
          value: "QA%Afhjsb5476"
        - name: standard.datasource.url
          value: "jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=${bd.port})(host=${bd.host}))(connect_data=(service_name=${bd.servicename}))(security=(ssl_server_dn_match=no)))"
        - name: standard.datasource.hikari.minimum-idle
          value: "10"
        - name: standard.datasource.hikari.maximum-pool-size
          value: "50"
        - name: standard.datasource.hikari.connectionTimeout
          value: "10000"
        - name: standard.datasource.hikari.idle-timeout
          value: "120000"
        - name: standard.datasource.hikari.max-lifetime
          value: "300000"
        - name: standard.datasource.hikari.validation-timeout
          value: "10000"
        - name: standard.datasource.hikari.connection-test-query
          value: "SELECT 1"
        - name: standard.datasource.hikari.initialization-fail-timeout
          value: "1"
        - name: standard.datasource.hikari.keep-alive-time
          value: "120000"
        - name: cache.duracionMinima
          value: "1"
        - name: cache.duracionMedia
          value: "2"
        - name: cache.duracionMaxima
          value: "3"
        - name: cache.duracion.login
          value: "30"
        - name: login.client_id
          value: "3c626b65-24c2-41f9-beb1-e36a84ef2957"
        - name: login.tenant_id
          value: "72fd0b5a-8a6a-4cff-89f6-bde961f7e250"
        - name: certificado_listado_api_url
          value: "http://10.10.150.34:8080/certificado-listado-service"
        - name: certificado_genera_api_url
          value: "http://10.10.150.34:8080/certificado-genera-service"
        - name: management.endpoint.health.show-details
          value: "always"
        - name: management.endpoints.web.exposure.include
          value: "*"
        - name: management.endpoints.web.exposure.exclude
          value: "conditions,shutdown"
---
apiVersion: v1
kind: Service
metadata:
  name: progresoacademico-lb-service
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.sa-santiago-1.aaaaaaaaccikvwaayqdghlmljscxczupri4qrcpalpgmthfhr7efjlyvwdna"
    # Anotaciones específicas para SSL
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: "backend-tls"
    service.beta.kubernetes.io/oci-load-balancer-ssl-protocols: "TLSv1.2,TLSv1.3"
    service.beta.kubernetes.io/oci-load-balancer-enable-http2: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
  selector:
    app: progresoacademico